name: Actions Workflow

on: 
  push: 
  pull_request:
    types: [closed, assigned, opened, reopened]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Listing files
        run: | 
            ls
            pwd
            ls -a
            echo $GITHUB_SHA
            echo $GITHUB_WORKSPACE
            echo $GITHUB_REPOSITORY
            echo "${{github.token}}"
      - name: Checkout
        uses: actions/checkout@v1
      - name: Listing files
        run: | 
            ls
            pwd
            ls -a
      - name: JS Actions
        uses: actions/hello-world-javascript-action@v1
        with:
              who-to-greet: Rathod
      - name: Logging greeting time as output
        run: echo "${{steps.greet.outputs.time}}"
