name: Actions Workflow

on: 
  push:
    branches:
      - master
      - 'feature/*'
      - 'feature/**'

    tags:
      - v1.*
    paths:
        - "**.js"   
        - '!filename.js' 
  

  # repository_dispatch:
  #   types: ['build'] 
  # push: 
  # pull_request:
  #   types: [closed, assigned, opened, reopened]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Client Payload
        run: echo ${{github.event.client_payload.env}}
      - name: Listing files
        run: | 
            ls
            pwd
            ls -a
            echo $GITHUB_SHA
            echo $GITHUB_WORKSPACE
            echo $GITHUB_REPOSITORY
            echo "${{github.token}}"
      - name: Checkout
        uses: actions/checkout@v1
      - name: Listing files
        run: | 
            ls
            pwd
            ls -a
      - name: JS Actions
        uses: actions/hello-world-javascript-action@v1
        with:
              who-to-greet: Rad
      - name: Logging greeting time as output
        run: echo "${{steps.greet.outputs.time}}"
