name: Containerization

on: push

jobs:
  docker-runs:
    runs-on: ubuntu-latest
    container:
      image: node:10.18.0-jessie
    steps:
      - name: Checking node version of first container
        run: node -v
      - name: Saying hello with docker and echo
        uses: docker://node:12.14.1-alpine3.10
        with:
              entrypoint: /bin/echo
              args: 'Hello everyone :)'     
      - uses: actions/checkout@v1        
      - name: Finding ways to say Hello
        uses: docker://node:12.14.1-alpine3.10
        with:
              entrypoint: ./script.sh
              args: "To someone out there."
 
  node-docker:
    runs-on: ubuntu-latest
    services:
      app:
        image: alialaa17/node-api
        ports:
            - 3001:3000
      mongo:
        image: mongo
        ports:
          - "27017:27017"
    steps:
      - name: Posting a user
        run: "curl -X POST http://localhost:3001/api/user -H 'Content-Type: application/json' -d '{\"username\": \"hello\",\"address\": \"dwded\"}'"
      - name: Get request for Users
        run: curl http://localhost:3001/api/users